import type { LocalStory } from "@/content/types";

const legacyMetadata = {
  status: "existing-prototype" as const,
  notes: "Migrated from legacy hardcoded Luganda story components into content_items-compatible story payloads.",
};

export const lugandaStories: LocalStory[] = [
  {
    id: "kintu",
    title: "The Tale of Kintu",
    summary: "Learn about Kintu, the first person on Earth according to Buganda mythology",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "kintu-page-1",
        text: "Long ago, Kintu was the first person on Earth. He lived alone with his cow, which was his only friend and source of food.",
        image: "story/kintu/kintu-cow.jpeg",
        altText: "Kintu standing beside his cow in a grassy field",
      },
      {
        id: "kintu-page-2",
        text: "Gulu, the god of the sky, had many children. His daughter, Nambi, saw Kintu and fell in love with him.",
        image: "story/kintu/nambi.jpeg",
        altText: "Nambi looking at Kintu from the sky",
      },
      {
        id: "kintu-page-3",
        text: "Nambi decided to marry Kintu and take him to live with her in the sky. But her father, Gulu, set difficult tests for Kintu to prove his worth.",
        image: "story/kintu/gulu-tests.jpeg",
        altText: "Gulu setting tests for Kintu",
      },
      {
        id: "kintu-page-4",
        text: "First, Kintu had to eat enormous amounts of food. With help from termites who secretly ate the food, Kintu passed the test.",
        image: "story/kintu/kintu-food.jpeg",
        altText: "Kintu eating food with termites helping",
      },
      {
        id: "kintu-page-5",
        text: "Then, Kintu had to find his special cow among thousands of identical cows. A bee helped him by landing on his cow's horn.",
        image: "story/kintu/kintu-cow-search.jpeg",
        altText: "Kintu finding his cow with the help of a bee",
      },
      {
        id: "kintu-page-6",
        text: "After passing all tests, Gulu allowed Kintu to marry Nambi. But he warned them to leave quickly and not come back, or Death would follow them.",
        image: "story/kintu/kintu-nambi.jpeg",
        altText: "Kintu and Nambi getting married",
      },
      {
        id: "kintu-page-7",
        text: "Nambi remembered she forgot to bring chicken feed. Despite Kintu's warning, she went back to get it. Death secretly followed them to Earth.",
        image: "story/kintu/death-follows.jpeg",
        altText: "Death following Kintu and Nambi to Earth",
      },
      {
        id: "kintu-page-8",
        text: "Kintu and Nambi started a family on Earth. They became the ancestors of the Baganda people. But because Death followed them, people don't live forever.",
        image: "story/kintu/kintu-family.jpeg",
        altText: "Kintu and Nambi with their family",
      },
    ],
    questions: [
      {
        id: "kintu-question-1",
        question: "Who was Kintu?",
        options: ["A god of the sky", "The first person on Earth", "Nambi's brother", "Gulu's son"],
        correctAnswer: 1,
      },
      {
        id: "kintu-question-2",
        question: "Who fell in love with Kintu?",
        options: ["Death", "Nambi", "Gulu", "A cow"],
        correctAnswer: 1,
      },
      {
        id: "kintu-question-3",
        question: "What tests did Gulu set for Kintu?",
        options: [
          "To find his cow and eat enormous amounts of food",
          "To climb the tallest mountain",
          "To defeat Death in battle",
          "To create the sun and moon",
        ],
        correctAnswer: 0,
      },
      {
        id: "kintu-question-4",
        question: "Why did Death follow Kintu and Nambi to Earth?",
        options: [
          "Because Gulu sent Death to watch over them",
          "Because Death was jealous of their happiness",
          "Because Nambi went back for chicken feed despite the warning",
          "Because Kintu challenged Death to a race",
        ],
        correctAnswer: 2,
      },
      {
        id: "kintu-question-5",
        question: "Who are the ancestors of the Baganda people according to this story?",
        options: [
          "Gulu and his children",
          "Death and his followers",
          "The termites who helped Kintu",
          "Kintu and Nambi",
        ],
        correctAnswer: 3,
      },
    ],
  },
  {
    id: "mwanga",
    title: "Kabaka Mwanga II",
    summary: "Discover the story of Kabaka Mwanga II of Buganda",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "mwanga-page-1",
        text: "Kabaka Mwanga II became the king of Buganda in 1884 when he was very young. He inherited a kingdom that was changing rapidly as Europeans brought new ideas and religions.",
        image: "story/mwanga/mwanga1.jpg",
        altText: "Young Kabaka Mwanga II being crowned as king",
      },
      {
        id: "mwanga-page-2",
        text: "At first, Mwanga allowed Christian missionaries to teach in his kingdom. Many Baganda people, including royal pages who served in the king's court, began to follow these new religions.",
        image: "story/mwanga/mwanga2.jpg",
        altText: "Missionaries teaching Baganda people at the royal court",
      },
      {
        id: "mwanga-page-3",
        text: "However, Mwanga became worried that his people's loyalty was shifting away from him and Buganda traditions. The new Christians were refusing to follow some of the king's orders.",
        image: "story/mwanga/mwanga3.jpg",
        altText: "Kabaka Mwanga looking concerned as people gather around missionaries",
      },
      {
        id: "mwanga-page-4",
        text: "In 1885, Mwanga ordered the execution of three missionary teachers. Later, he commanded that many converted Baganda Christians be put to death at Namugongo for their disobedience.",
        image: "story/mwanga/mwanga4.jpg",
        altText: "A solemn scene representing the martyrs of Namugongo",
      },
      {
        id: "mwanga-page-5",
        text: "These people became known as the Uganda Martyrs. Their bravery inspired even more Baganda people to become Christians, which was the opposite of what Mwanga had intended.",
        image: "story/mwanga/mwanga5.jpg",
        altText: "People gathering to honor the memory of the martyrs",
      },
      {
        id: "mwanga-page-6",
        text: "As European influence grew, Mwanga faced many challenges to his rule. In 1888, he was overthrown but fought to regain his throne. Later, he resisted British colonial control.",
        image: "story/mwanga/mwanga6.jpg",
        altText: "Mwanga leading resistance against colonial forces",
      },
      {
        id: "mwanga-page-7",
        text: "In 1899, Mwanga was captured by the British and exiled to the Seychelles Islands, far from his homeland. He never returned to Buganda and died in exile in 1903.",
        image: "story/mwanga/mwanga7.jpg",
        altText: "Mwanga being taken away on a ship to exile",
      },
      {
        id: "mwanga-page-8",
        text: "Today, Kabaka Mwanga is remembered as a complex figure in Buganda's history—a king who fought to preserve his kingdom's independence during a time of great change and outside influence.",
        image: "story/mwanga/mwanga8.jpg",
        altText: "A memorial to Kabaka Mwanga with both traditional and modern elements",
      },
    ],
    questions: [
      {
        id: "mwanga-question-1",
        question: "When did Kabaka Mwanga II become king of Buganda?",
        options: ["1776", "1825", "1884", "1901"],
        correctAnswer: 2,
      },
      {
        id: "mwanga-question-2",
        question: "What worried Mwanga about the Christian missionaries?",
        options: [
          "They were teaching people to read",
          "People's loyalty was shifting away from him and traditions",
          "They were building too many churches",
          "They wanted his crown",
        ],
        correctAnswer: 1,
      },
      {
        id: "mwanga-question-3",
        question: "What happened at Namugongo?",
        options: [
          "A new palace was built",
          "Converted Baganda Christians were executed",
          "Mwanga was crowned",
          "Europeans established a trading post",
        ],
        correctAnswer: 1,
      },
      {
        id: "mwanga-question-4",
        question: "What effect did the martyrs' deaths have?",
        options: [
          "Christianity disappeared from Buganda",
          "Even more Baganda people became Christians",
          "Mwanga became more powerful",
          "The missionaries left Uganda",
        ],
        correctAnswer: 1,
      },
      {
        id: "mwanga-question-5",
        question: "What happened to Kabaka Mwanga in 1899?",
        options: [
          "He was captured by the British and exiled",
          "He defeated the British forces",
          "He converted to Christianity",
          "He united all Ugandan kingdoms",
        ],
        correctAnswer: 0,
      },
    ],
  },
  {
    id: "kasubi-tombs",
    title: "Kasubi Tombs Story",
    summary: "Explore the UNESCO World Heritage Site of Kasubi Tombs",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "kasubi-tombs-page-1",
        text: "The story of Kasubi Tombs begins with Kabaka Mutesa I, who ruled Buganda from 1856 to 1884. He was a powerful king who established contact with Arab traders and European explorers.",
        image: "coin.png",
        altText: "Kabaka Mutesa I sitting in royal attire meeting with visitors",
      },
      {
        id: "kasubi-tombs-page-2",
        text: "In 1882, Mutesa I built his palace at Kasubi Hill. It was a magnificent traditional building called Muzibu-Azaala-Mpanga, with a large circular thatched roof and walls made of reeds.",
        image: "coin.png",
        altText: "Construction of the grand palace with traditional materials",
      },
      {
        id: "kasubi-tombs-page-3",
        text: "When Kabaka Mutesa I died in 1884, the Baganda people decided to bury him inside his own palace. This was unusual, as kings were typically buried at different sites around the kingdom.",
        image: "coin.png",
        altText: "A funeral procession bringing Mutesa I to his final resting place",
      },
      {
        id: "kasubi-tombs-page-4",
        text: "The palace was converted into a royal tomb, and a sacred place where people could connect with the spirit of their beloved king. Special caretakers called Naalinya, royal princesses, were appointed to tend to the site.",
        image: "coin.png",
        altText: "Naalinya princesses tending to the royal tomb",
      },
      {
        id: "kasubi-tombs-page-5",
        text: "After Mutesa I, three more Buganda kings (Mwanga II, Daudi Chwa II, and Edward Mutesa II) were also buried at Kasubi. Each king has a sacred shrine within the main building.",
        image: "coin.png",
        altText: "The four royal burial areas within the main building",
      },
      {
        id: "kasubi-tombs-page-6",
        text: "The tombs became a center of Buganda spiritual life. The main tomb house represents the entire kingdom, with the central poles symbolizing the clans of Buganda and the king as their unifier.",
        image: "coin.png",
        altText: "People gathering at the tombs for spiritual ceremonies",
      },
      {
        id: "kasubi-tombs-page-7",
        text: "Inside the tombs are royal treasures, including the kings' jawbones, which the Baganda believe contain the spirits of the deceased kings. These are kept behind a sacred bark cloth curtain.",
        image: "coin.png",
        altText: "Sacred bark cloth curtains protecting royal artifacts",
      },
      {
        id: "kasubi-tombs-page-8",
        text: "In 2001, UNESCO declared Kasubi Tombs a World Heritage Site. Though damaged by fire in 2010, the tombs were rebuilt and continue to be a vital cultural treasure for the Baganda people and all Ugandans.",
        image: "coin.png",
        altText: "The restored Kasubi Tombs with visitors learning about Buganda heritage",
      },
    ],
    questions: [
      {
        id: "kasubi-tombs-question-1",
        question: "Who built the palace that later became Kasubi Tombs?",
        options: ["Kabaka Mwanga II", "Kabaka Mutesa I", "British colonizers", "Daudi Chwa II"],
        correctAnswer: 1,
      },
      {
        id: "kasubi-tombs-question-2",
        question: "When was the palace at Kasubi Hill built?",
        options: ["1700", "1802", "1882", "1920"],
        correctAnswer: 2,
      },
      {
        id: "kasubi-tombs-question-3",
        question: "What was unusual about Mutesa I's burial?",
        options: [
          "He was buried with all his possessions",
          "He was buried standing up",
          "He was buried inside his own palace",
          "He was buried in a foreign land",
        ],
        correctAnswer: 2,
      },
      {
        id: "kasubi-tombs-question-4",
        question: "Who are the Naalinya?",
        options: [
          "Male warriors",
          "Royal princesses who care for the tombs",
          "Foreign visitors",
          "Religious leaders",
        ],
        correctAnswer: 1,
      },
      {
        id: "kasubi-tombs-question-5",
        question: "How many Buganda kings are buried at Kasubi Tombs?",
        options: ["Two", "Four", "Seven", "Ten"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "walumbe",
    title: "The Tale of Walumbe",
    summary: "Learn about the story of Walumbe and the origin of death",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "walumbe-page-1",
        text: "After Kintu and Nambi came to Earth, they were followed by Walumbe, who was Death, Nambi's brother. At first, Walumbe lived peacefully among the people.",
        image: "coin.png",
        altText: "Walumbe arriving on Earth after Kintu and Nambi",
      },
      {
        id: "walumbe-page-2",
        text: "One day, Walumbe asked Kintu to give him one of his daughters as a wife. Kintu refused, knowing that no good could come from such a union with Death.",
        image: "coin.png",
        altText: "Walumbe speaking with Kintu who refuses his request",
      },
      {
        id: "walumbe-page-3",
        text: "Angered by the rejection, Walumbe began to take Kintu's children, one by one. He would hide them underground in the caverns where he lived, causing great sorrow.",
        image: "coin.png",
        altText: "Walumbe taking children into underground caverns",
      },
      {
        id: "walumbe-page-4",
        text: "Kintu appealed to Gulu, the sky god. Gulu sent his son, Kayikuuzi, to capture Walumbe and take him back to the sky so he would stop bringing death to Earth.",
        image: "coin.png",
        altText: "Kintu appealing to Gulu in the sky",
      },
      {
        id: "walumbe-page-5",
        text: "Kayikuuzi chased Walumbe across the land. Finally, Walumbe fled into the ground at a place now called Ttanda, and Kayikuuzi followed him into the deep caves.",
        image: "coin.png",
        altText: "Kayikuuzi chasing Walumbe who is diving into the ground",
      },
      {
        id: "walumbe-page-6",
        text: "The chase went on for days. Each time Kayikuuzi almost caught Walumbe, the people above ground would make noise, warning Walumbe, who would escape deeper into the earth.",
        image: "coin.png",
        altText: "People making noise above ground as the chase continues below",
      },
      {
        id: "walumbe-page-7",
        text: "Eventually, Kayikuuzi gave up. He told the people, 'Because you warned Walumbe, I cannot capture him. Now death will remain on Earth forever.'",
        image: "coin.png",
        altText: "Kayikuuzi emerging from the ground speaking to the people",
      },
      {
        id: "walumbe-page-8",
        text: "To this day, the Baganda say that Walumbe still lives in the caves of Ttanda, and that is why death comes to all people. The caves remain a sacred and feared place.",
        image: "coin.png",
        altText: "The caves of Ttanda with people paying respects from a distance",
      },
    ],
    questions: [
      {
        id: "walumbe-question-1",
        question: "Who was Walumbe in relation to Nambi?",
        options: ["Her father", "Her husband", "Her brother", "Her son"],
        correctAnswer: 2,
      },
      {
        id: "walumbe-question-2",
        question: "What did Walumbe ask from Kintu?",
        options: ["A piece of land", "One of his daughters as a wife", "Help building a home", "Food and shelter"],
        correctAnswer: 1,
      },
      {
        id: "walumbe-question-3",
        question: "What did Walumbe do when Kintu refused his request?",
        options: [
          "Left peacefully",
          "Began taking Kintu's children one by one",
          "Asked Gulu for help",
          "Built his own kingdom",
        ],
        correctAnswer: 1,
      },
      {
        id: "walumbe-question-4",
        question: "Who did Gulu send to capture Walumbe?",
        options: ["Nambi", "Kintu", "Kayikuuzi", "A powerful animal"],
        correctAnswer: 2,
      },
      {
        id: "walumbe-question-5",
        question: "Why couldn't Kayikuuzi capture Walumbe?",
        options: [
          "Walumbe was too strong",
          "The people warned Walumbe by making noise",
          "Gulu changed his mind",
          "Kintu protected Walumbe",
        ],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "ssezibwa",
    title: "Ssezibwa Falls",
    summary: "Follow the historical origin of Ssezibwa Falls",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "ssezibwa-page-1",
        text: "Long ago in Buganda, a woman named Nakkungu Tebatuusa was expecting twins. As she traveled to visit her parents, something extraordinary happened.",
        image: "coin.png",
        altText: "A pregnant woman traveling through the countryside",
      },
      {
        id: "ssezibwa-page-2",
        text: "Instead of giving birth to children, Nakkungu gave birth to two rivers. The first river was Ssezibwa, a boy river. The second was Bwanda, a girl river.",
        image: "coin.png",
        altText: "Rivers flowing from a mountainside",
      },
      {
        id: "ssezibwa-page-3",
        text: "The Ssezibwa River flowed strongly eastward, cutting through rocks and creating beautiful waterfalls. The river spoke to his mother, telling her not to worry.",
        image: "coin.png",
        altText: "Powerful waterfall flowing through rocks",
      },
      {
        id: "ssezibwa-page-4",
        text: "\"I will be more useful as a river than as a human,\" Ssezibwa said. \"I will provide water for animals, plants, and people. I will be remembered forever.\"",
        image: "coin.png",
        altText: "Animals drinking from the river",
      },
      {
        id: "ssezibwa-page-5",
        text: "The Buganda people believed that Ssezibwa Falls was a special place where spirits lived. People would visit the falls to make offerings and ask for blessings.",
        image: "coin.png",
        altText: "People making offerings at the waterfall",
      },
      {
        id: "ssezibwa-page-6",
        text: "If someone needed good fortune, they would throw cowrie shells or coins into the water. Farmers would ask for rain, and fishermen would ask for a good catch.",
        image: "coin.png",
        altText: "People throwing offerings into the river",
      },
      {
        id: "ssezibwa-page-7",
        text: "Even powerful kings of Buganda would visit Ssezibwa Falls before important battles or decisions. They believed the river spirit would give them wisdom and strength.",
        image: "coin.png",
        altText: "A king visiting the falls with attendants",
      },
      {
        id: "ssezibwa-page-8",
        text: "To this day, Ssezibwa Falls remains a sacred place in Uganda. The river that began as a child continues to nurture life and inspire wonder in all who visit.",
        image: "coin.png",
        altText: "Modern visitors admiring the beautiful falls",
      },
    ],
    questions: [
      {
        id: "ssezibwa-question-1",
        question: "What was unusual about Nakkungu Tebatuusa's birth experience?",
        options: ["She gave birth to twins", "She gave birth to rivers", "She gave birth in a waterfall", "She gave birth to spirits"],
        correctAnswer: 1,
      },
      {
        id: "ssezibwa-question-2",
        question: "What were the names of the two rivers born to Nakkungu?",
        options: ["Nile and Victoria", "Kagera and Katonga", "Ssezibwa and Bwanda", "Mabira and Mpanga"],
        correctAnswer: 2,
      },
      {
        id: "ssezibwa-question-3",
        question: "Why did Ssezibwa say he would be more useful as a river?",
        options: [
          "To avoid human responsibilities",
          "To provide water for animals, plants, and people",
          "To create beautiful waterfalls",
          "To connect to other rivers",
        ],
        correctAnswer: 1,
      },
      {
        id: "ssezibwa-question-4",
        question: "What did people throw into Ssezibwa Falls to ask for good fortune?",
        options: ["Flowers and fruits", "Cowrie shells or coins", "Wooden carvings", "Clay pots"],
        correctAnswer: 1,
      },
      {
        id: "ssezibwa-question-5",
        question: "Who would visit Ssezibwa Falls before important battles or decisions?",
        options: ["Fishermen", "Farmers", "Kings of Buganda", "Foreign visitors"],
        correctAnswer: 2,
      },
    ],
  },
  {
    id: "millet",
    title: "Nnambi and the Millet",
    summary: "Discover the story of Nambi and the first millet",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "millet-page-1",
        text: "Long ago when the Baganda people first settled in their lands, they did not know how to grow food. They survived by hunting animals and gathering wild fruits.",
        image: "coin.png",
        altText: "People hunting and gathering wild fruits",
      },
      {
        id: "millet-page-2",
        text: "A woman named Nnambi lived with her husband in a small hut. Each day grew harder as there were more people but less food to be found in the forests.",
        image: "coin.png",
        altText: "Nnambi and her husband looking worried about food",
      },
      {
        id: "millet-page-3",
        text: "One night, Nnambi had a dream. A beautiful spirit came to her and said, 'Follow the morning star until you reach the red hill. There you will find what your people need.'",
        image: "coin.png",
        altText: "Nnambi dreaming of a spirit speaking to her",
      },
      {
        id: "millet-page-4",
        text: "When she awoke, Nnambi told no one about her dream. Before sunrise, she followed the morning star, walking for many hours until she reached a hill with reddish soil.",
        image: "coin.png",
        altText: "Nnambi walking alone following the morning star",
      },
      {
        id: "millet-page-5",
        text: "On the hill grew tall plants with golden seeds that Nnambi had never seen before. The spirit appeared again and said, 'This is millet. Take these seeds and learn to grow them.'",
        image: "coin.png",
        altText: "Nnambi discovering millet plants on the red hill",
      },
      {
        id: "millet-page-6",
        text: "The spirit showed Nnambi how to plant the seeds, tend the young plants, and harvest the grain when it was ripe. She also learned how to grind the millet and cook it.",
        image: "coin.png",
        altText: "The spirit teaching Nnambi how to plant and prepare millet",
      },
      {
        id: "millet-page-7",
        text: "Nnambi returned to her village carrying the precious millet seeds. She taught everyone what she had learned, and soon fields of golden millet were growing throughout the land.",
        image: "coin.png",
        altText: "Nnambi sharing millet seeds with villagers",
      },
      {
        id: "millet-page-8",
        text: "The Baganda people no longer went hungry. They honored Nnambi as a hero, and to this day, millet porridge is a sacred food in Buganda, used in many important ceremonies and celebrations.",
        image: "coin.png",
        altText: "People celebrating with millet porridge at a ceremony",
      },
    ],
    questions: [
      {
        id: "millet-question-1",
        question: "How did the Baganda people survive before they knew how to grow food?",
        options: [
          "By trading with neighbors",
          "By hunting animals and gathering wild fruits",
          "By fishing in lakes",
          "By stealing from other tribes",
        ],
        correctAnswer: 1,
      },
      {
        id: "millet-question-2",
        question: "What did the spirit in Nnambi's dream tell her to do?",
        options: ["Build a new village", "Follow the morning star to the red hill", "Pray to the ancestors", "Search for a hidden treasure"],
        correctAnswer: 1,
      },
      {
        id: "millet-question-3",
        question: "What did Nnambi discover on the red hill?",
        options: ["Gold and jewels", "A magic spring", "Tall plants with golden seeds (millet)", "A new type of animal"],
        correctAnswer: 2,
      },
      {
        id: "millet-question-4",
        question: "What did the spirit teach Nnambi?",
        options: [
          "How to hunt better",
          "How to plant, tend, harvest, and cook millet",
          "How to predict the weather",
          "How to make clothing",
        ],
        correctAnswer: 1,
      },
      {
        id: "millet-question-5",
        question: "Why is millet porridge considered sacred in Buganda?",
        options: [
          "Because it has healing properties",
          "Because it is used in many important ceremonies",
          "Because only royalty can eat it",
          "Because it glows in the dark",
        ],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "kasokambirye",
    title: "Kasokambirye and the Moon",
    summary: "Discover the story of Kasokambirye and the moon",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "kasokambirye-page-1",
        text: "In the kingdom of Buganda, there was a brave hunter named Kasokambirye. He was known for his incredible aim with a spear and his fearless heart.",
        image: "coin.png",
        altText: "A hunter with a spear standing proudly",
      },
      {
        id: "kasokambirye-page-2",
        text: "One night, Kasokambirye looked up at the bright full moon. 'Why does the moon glow so brightly while we must live in darkness?' he wondered aloud.",
        image: "coin.png",
        altText: "Kasokambirye looking up at the full moon",
      },
      {
        id: "kasokambirye-page-3",
        text: "His friends laughed at him. 'No one can reach the moon! It is too far away,' they said. But Kasokambirye was determined to prove them wrong.",
        image: "coin.png",
        altText: "Friends laughing as Kasokambirye points at the moon",
      },
      {
        id: "kasokambirye-page-4",
        text: "Kasokambirye began to build a tower of trees, climbing higher and higher towards the sky. He worked for many days and nights, never stopping to rest.",
        image: "coin.png",
        altText: "Kasokambirye building a tall tower of trees",
      },
      {
        id: "kasokambirye-page-5",
        text: "Finally, his tower reached so high that he could almost touch the moon. 'Just one more tree!' he called down to his friends. 'Then I will bring the moon to Earth!'",
        image: "coin.png",
        altText: "Kasokambirye at the top of his tower reaching for the moon",
      },
      {
        id: "kasokambirye-page-6",
        text: "But as he placed the last tree on his tower, the structure began to sway. The wind blew strongly, and the tower tumbled down, taking Kasokambirye with it.",
        image: "coin.png",
        altText: "The tower collapsing as Kasokambirye falls",
      },
      {
        id: "kasokambirye-page-7",
        text: "As he fell, Kasokambirye grabbed onto the moon. Instead of bringing the moon down, the moon pulled him up. To everyone's amazement, he disappeared into the sky.",
        image: "coin.png",
        altText: "Kasokambirye being pulled up to the moon",
      },
      {
        id: "kasokambirye-page-8",
        text: "The Baganda people say that on clear nights, you can see Kasokambirye's silhouette on the moon. His courage and ambition remind us to always reach for the stars.",
        image: "coin.png",
        altText: "A silhouette visible on the full moon",
      },
    ],
    questions: [
      {
        id: "kasokambirye-question-1",
        question: "What was Kasokambirye known for?",
        options: [
          "His wisdom and patience",
          "His incredible aim with a spear and fearless heart",
          "His ability to talk to animals",
          "His skill at building houses",
        ],
        correctAnswer: 1,
      },
      {
        id: "kasokambirye-question-2",
        question: "Why did Kasokambirye want to reach the moon?",
        options: ["To prove his friends wrong", "To bring light to Earth during night", "To meet moon spirits", "To become famous"],
        correctAnswer: 1,
      },
      {
        id: "kasokambirye-question-3",
        question: "How did Kasokambirye try to reach the moon?",
        options: ["By climbing a mountain", "By building a tower of trees", "By taming a giant bird", "By using magic"],
        correctAnswer: 1,
      },
      {
        id: "kasokambirye-question-4",
        question: "What happened when Kasokambirye's tower collapsed?",
        options: ["He fell back to Earth", "He grabbed onto the moon and was pulled up", "He was rescued by his friends", "He built another tower"],
        correctAnswer: 1,
      },
      {
        id: "kasokambirye-question-5",
        question: "According to the story, what can be seen on clear nights?",
        options: [
          "Kasokambirye's tower reaching to the sky",
          "Kasokambirye's silhouette on the moon",
          "The path Kasokambirye took to the moon",
          "Kasokambirye's spear floating in the sky",
        ],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: "fig-tree",
    title: "The Generous Fig Tree",
    summary: "Discover the story of the generous fig tree",
    languageCode: "lg",
    metadata: legacyMetadata,
    pages: [
      {
        id: "fig-tree-page-1",
        text: "In a small village in Buganda, there grew a magnificent Mutuba fig tree. Its branches stretched wide, providing shade for everyone in the village.",
        image: "coin.png",
        altText: "A large fig tree providing shade to villagers",
      },
      {
        id: "fig-tree-page-2",
        text: "The tree was not just any tree—it produced the bark cloth that was precious to the Baganda people. This cloth was used for ceremonial robes, bedding, and even burial shrouds.",
        image: "coin.png",
        altText: "People making bark cloth from the fig tree",
      },
      {
        id: "fig-tree-page-3",
        text: "A poor woman named Nakawala lived near the tree. Each day, the tree would drop a single fig at her doorstep, which she would eat to survive.",
        image: "coin.png",
        altText: "A woman picking up a fig from her doorstep",
      },
      {
        id: "fig-tree-page-4",
        text: "The village chief noticed how healthy Nakawala looked despite her poverty. He became curious and decided to watch her house to discover her secret.",
        image: "coin.png",
        altText: "The chief watching the woman's house from a distance",
      },
      {
        id: "fig-tree-page-5",
        text: "When he saw the fig tree drop its fruit for Nakawala, he became greedy. 'If one fig makes her so healthy, what would happen if I ate all the figs?' he thought.",
        image: "coin.png",
        altText: "The chief looking greedily at the fig tree",
      },
      {
        id: "fig-tree-page-6",
        text: "The chief ordered his men to collect every fig from the tree, leaving none for Nakawala or the birds and animals that depended on it. They took baskets full of figs to his home.",
        image: "coin.png",
        altText: "Men collecting all the figs from the tree in baskets",
      },
      {
        id: "fig-tree-page-7",
        text: "That night, a terrible storm came. Lightning struck the chief's house, destroying only the room where the figs were stored. The next morning, the fig tree had disappeared completely.",
        image: "coin.png",
        altText: "Lightning striking the chief's house during a storm",
      },
      {
        id: "fig-tree-page-8",
        text: "But a new sapling appeared at Nakawala's doorstep. The tree had chosen to move where it was appreciated. The Baganda learned that generosity should be met with gratitude, not greed.",
        image: "coin.png",
        altText: "A small fig tree sapling growing at the woman's doorstep",
      },
    ],
    questions: [
      {
        id: "fig-tree-question-1",
        question: "What was special about the Mutuba fig tree?",
        options: [
          "It could talk",
          "It produced bark cloth precious to the Baganda",
          "It had golden leaves",
          "It never lost its leaves in dry season",
        ],
        correctAnswer: 1,
      },
      {
        id: "fig-tree-question-2",
        question: "How did the fig tree help Nakawala?",
        options: [
          "By telling her stories",
          "By dropping a single fig at her doorstep each day",
          "By providing shade for her house",
          "By healing her illnesses",
        ],
        correctAnswer: 1,
      },
      {
        id: "fig-tree-question-3",
        question: "Why did the village chief become interested in Nakawala?",
        options: [
          "He wanted to marry her",
          "He noticed how healthy she looked despite her poverty",
          "He wanted her land",
          "He thought she was stealing from others",
        ],
        correctAnswer: 1,
      },
      {
        id: "fig-tree-question-4",
        question: "What did the chief do when he discovered the fig tree's gift?",
        options: [
          "He thanked the tree",
          "He ordered his men to collect every fig from the tree",
          "He shared the figs with everyone",
          "He planted more fig trees",
        ],
        correctAnswer: 1,
      },
      {
        id: "fig-tree-question-5",
        question: "What lesson does this story teach?",
        options: [
          "Trees are more valuable than gold",
          "Generosity should be met with gratitude, not greed",
          "Chiefs always know best",
          "Poor people are often the wisest",
        ],
        correctAnswer: 1,
      },
    ],
  },
];
